//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using SimpleJSON;

public class PersonalAvatar : MonoBehaviour
{
	public RectTransform pfImageView;
	public RectTransform gridView;

	void Start ()
	{
		string uid = GameApplication.user.tinyURL;
		if(uid.Contains("fb.")){
			string url = Utils.buildFBAvatar(uid.Replace("fb.",""));
			addItem(url, 0);
		}
		for (int i = 1 ; i < 32; i++) {
			if(GameApplication.gameApp == GameApplication.GameApp.DauTruong)
				addItem (Utils.buildAvatar (i), i);
			else if(GameApplication.gameApp == GameApplication.GameApp.G3C)
				addItem (Utils.buildAvatar (i), i);
			else if(GameApplication.gameApp == GameApplication.GameApp.G52Fun)
				addItem (Utils.buildAvatar (i), i);
		}
	}

	public void addItem (string url, int i)
	{
		Image img = GameObject.Instantiate (pfImageView).GetComponent<Image> ();
		img.rectTransform.SetParent (gridView, false);
		SuperScene.instance.loadImage (url, img, null);
		img.transform.GetComponent<Button> ().onClick.AddListener (delegate() {
			var data = new JSONClass ();
			data ["evt"] = "changea";
			data ["A"].AsInt = i;
			GameApplication.inChangingAvatar = i;
			GameApplication.cubeia.sendService (data);
			GameApplication.user.avatarUrl = url;
		});
	}
}

