//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace com.dst.Roulette
{
	public class PathSound
	{
		private string name;
		private float vol;
		private float time;

		public PathSound (string au, float v, float t)
		{
			name = au;
			vol = v;
			time = t;
		}

		public override  string ToString ()
		{
			return "\""+ name + ":" + vol + ":" + time + "\"";
			//return ("\"" + audio + ":" +  volume.ToString("0.00") + ":" + time.ToString("0.00") +"\""); 
		}
		
	}
}

