//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SimpleJSON;
using System.Collections.Generic;

public class DailyBonus
{
	public  int money;
	public static List<DailyBonus> listDailyBonus = new List<DailyBonus> ();

	public  static void init (JSONArray jarr)
	{
		for (int i=0; i<jarr.Count; i++) {
			listDailyBonus.Add (new DailyBonus (jarr [i].AsInt));
		}
	}

	public DailyBonus (int money)
	{
		this.money = money;
	}
}
