//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using SimpleJSON;

public class ShowDailyBonus : MonoBehaviour
{
	public Text title;
	public Text[] day = new Text[5];
	public Text[] money = new Text[5];
	public RectTransform[] p_day = new RectTransform[5];

	void Start ()
	{
		this.title.text = Strings.instance.quahangngay;
		this.day [0].text = Strings.instance.quahangngay_day1;
		this.day [1].text = Strings.instance.quahangngay_day2;
		this.day [2].text = Strings.instance.quahangngay_day3;
		this.day [3].text = Strings.instance.quahangngay_day4;
		this.day [4].text = Strings.instance.quahangngay_day5;

		for (int i=0; i<5; i++) {
			// rat nguy hiem neu khong lay dc DailyBonus.listDailyBonus khi get config.
			// gay loi Argument is out of range
			this.money [i].text = Utils.formatNumber (DailyBonus.listDailyBonus [i].money);
			if (i >= User.od) {
				p_day [i].GetComponent<Image> ().color = new Color32 (179, 195, 195, 166);
			}
			if (i == User.od - 1) {
				p_day [i].GetComponent<Image> ().transform.localScale = new Vector3 (1.0f, 1.15f, 1.0f);
			}
			if (User.od >= 6) {
				p_day [4].GetComponent<Image> ().transform.localScale = new Vector3 (1.0f, 1.15f, 1.0f);
			}
		}

	}

	public void sendDaily ()
	{

		var data = new JSONClass ();
		data ["evt"] = "dp";
		data ["day"].AsInt = User.od;
//		string input = "{\"evt\":\"dp\", \"day\":1}";
		GameApplication.cubeia.sendService (data);
		
	}
}

